// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6fWzVaxIEcAza2Ct2I1Kfp9KIJF5bGKI',
    appId: '1:488668203531:web:e3875088522d6698cc950e',
    messagingSenderId: '488668203531',
    projectId: 'rayshop-7063a',
    authDomain: 'rayshop-7063a.firebaseapp.com',
    storageBucket: 'rayshop-7063a.appspot.com',
    measurementId: 'G-651WJQHWCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtZLFaITGWSOerP1q2DS7K9KUjTOAVqHI',
    appId: '1:488668203531:android:5325a71573498a39cc950e',
    messagingSenderId: '488668203531',
    projectId: 'rayshop-7063a',
    storageBucket: 'rayshop-7063a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3nR1TNb6VYv0edn2Hzj3ohsDHQv03BsE',
    appId: '1:488668203531:ios:8faddf9886aa5bcacc950e',
    messagingSenderId: '488668203531',
    projectId: 'rayshop-7063a',
    storageBucket: 'rayshop-7063a.appspot.com',
    iosClientId: '488668203531-8309mhpe92e5krdt8i2eo02lk4135g3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.rayshop',
  );
}
